insert into brands(id,descrip) values (1,'Reanult');
insert into brands(id,descrip) values (2,'Seat');
insert into brands(id,descrip) values (3,'Mercedes');
insert into models(id,brand_id,descrip) values (1,1,'Captur');
insert into models(id,brand_id,descrip) values (2,1,'Kadjar');
insert into models(id,brand_id,descrip) values (3,2,'Ateca');
insert into models(id,brand_id,descrip) values (4,2,'Arona');
insert into models(id,brand_id,descrip) values (5,3,'CLK 320');
insert into cars(id,model_id,numberplate,price) values (1,1,'1587CVF',12000);
insert into cars(id,model_id,numberplate,price) values (2,4,'258RTY',22000);
insert into cars(id,model_id,numberplate,price) values (3,4,'9857POY',250000);
insert into cars(id,model_id,numberplate,price) values (4,5,'0254SDE',250000);